bundler_args: --without development
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - ruby-head
gemfile:
  - gemfiles/activesupport3.0-rpsec2.6.gemfile
  - gemfiles/activesupport3.0-rpsec2.7.gemfile
  - gemfiles/activesupport3.1-rpsec2.6.gemfile
  - gemfiles/activesupport3.1-rpsec2.7.gemfile
