bundler_args: --without development
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - ruby-head
gemfile:
  - gemfiles/activesupport3.0-rspec2.6.gemfile
  - gemfiles/activesupport3.0-rspec2.7.gemfile
  - gemfiles/activesupport3.0-rspec2.8.gemfile
  - gemfiles/activesupport3.0-rspec2.9.gemfile
  - gemfiles/activesupport3.1-rspec2.6.gemfile
  - gemfiles/activesupport3.1-rspec2.7.gemfile
  - gemfiles/activesupport3.1-rspec2.8.gemfile
  - gemfiles/activesupport3.1-rspec2.9.gemfile
  - gemfiles/activesupport3.2-rspec2.6.gemfile
  - gemfiles/activesupport3.2-rspec2.7.gemfile
  - gemfiles/activesupport3.2-rspec2.8.gemfile
  - gemfiles/activesupport3.2-rspec2.9.gemfile
